[[redirects]]
  from = "https://education.cardanofoundation.org/"
  to = "https://academy.cardanofoundation.org/"
  status = 301
  force = true

[[redirects]]
  from = "https://education.cardano.org/"
  to = "https://academy.cardanofoundation.org/"
  status = 301
  force = true

[[redirects]]
  from = "https://academy.cardano.org/"
  to = "https://academy.cardanofoundation.org/"
  status = 301
  force = true