import './globals.css'
import { Chivo } from 'next/font/google'
import Navigation from '@/components/Navigation'

const chivo = Chivo({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={chivo.className}>
        <header>
          <Navigation />
        </header>
        {children}
      </body>
    </html>
  )
}
